inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3
