inherit_from: .rubocop_todo.yml

inherit_gem:
  pundit: config/rubocop-rspec.yml

require:
  - rubocop-rails
  - rubocop-rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Layout/FirstArrayElementIndentation:
  Enabled: false
