# fly.toml app configuration file generated for socialchange on 2023-08-31T17:10:53+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "socialchange"
primary_region = "ams"
console_command = "bin/rails console"

[build]
  dockerfile = "Dockerfile.production"

[deploy]
  release_command = "bin/rails db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
