name: Deploy

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches:
      - production

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success'
    concurrency: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: dentarg/fly@v1
        with:
          fly-token: ${{ secrets.FLY_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
