name: Deploy production

on:
  workflow_run:
    workflows: [Tests]
    types: [completed]
    branches:
      - production

jobs:
  deploy:
    name: Deploy
    if: |
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: production
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: 1.4
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
