name: reviewdog
on: [pull_request]

permissions:
  contents: read
  pull-requests: write
jobs:
  standardrb:
    name: runner / standardrb
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Setup Ruby based on .ruby-version
        uses: ruby/setup-ruby@v1
      - name: Restore bundle cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{runner.os}}-gems-${{hashFiles('**/Gemfile.lock')}}
          restore-keys: ${{runner.os}}-gems-

      - name: Bundle install
        run: |
          bundle install
      - name: StandardRB Action
        uses: andrewmcodes/standardrb-action@v0.0.2
